version: "3.8"

services:
  backend_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8000"
    container_name: docktor_backend
    depends_on:
      - database_service
    env_file:
      - .env
    networks:
      - local

  database_service:
    image: postgres:16
    container_name: docktor_database
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - local
    env_file:
      - .env
volumes:
  rabbitmq_data:
  pg_data:

networks:
  local: